apiVersion: apps/v1
kind: Deployment
metadata:
  name: luisciber-blog
  labels:
    role: luisciber-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      role: luisciber-blog
  template:
    metadata:
      labels:
        role: luisciber-blog
    spec:
      containers:
        - name: http-server
          image: correaleyval/luisciber-blog:100721
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: luisciber-blog
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    role: luisciber-blog
